### ISSUE TITLE
Just saying but...

### ISSUE THREAD

**Issue by agucova** [maliceio/maliceio#1]
Maybe even using a template for github pages could hold up a while? It's better than just a redirection. 👍 

Maybe Sinatra, Slate or Midnight...

**Comment by blacktop** [comment]
I agree.  I have something very specific in mind for malice.io, I just need to get malice to a MVP first.  Thank you for your interest.

**Comment by blacktop** [comment]
whoa actually I didn't know it was doing that weird redirect??? It must have been recycled by digital ocean.  Thanks for the heads up

**Comment by blacktop** [comment]
https://malice.io there you go 😉
